name: lost_n_found_mobile
description: "Lost and Found App - Softawrica College"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # ---------------- STATE MANAGEMENT ----------------
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # ---------------- LOCAL DATABASE ----------------
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  path_provider: ^2.1.5
  path: ^1.9.1

  # ---------------- NETWORKING ----------------
  dio: ^5.9.0
  dio_smart_retry: ^7.0.1
  connectivity_plus: ^7.0.0

  # ---------------- AUTH ----------------
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.5.4
  jwt_decoder: ^2.0.1
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1

  # ---------------- MEDIA ----------------
  flutter_image_compress: ^2.4.0
  video_compress: ^3.1.4
  image_picker: ^1.2.1
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  video_thumbnail: ^0.5.6
  flutter_svg: ^2.2.3

  # ---------------- REALTIME ----------------
  web_socket_channel: ^3.0.3

  # ---------------- UTILITIES ----------------
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  either_dart: ^1.0.0
  uuid: ^4.5.2
  intl: ^0.20.2

  # ---------------- BACKGROUND ----------------
  workmanager: ^0.9.0+3

  # ---------------- PERMISSIONS ----------------
  permission_handler: ^12.0.1
  equatable: ^2.0.7
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  riverpod_generator: ^2.4.0
  json_serializable: ^6.8.0
  freezed: ^2.5.2

  mocktail: ^1.0.4
  fake_async: ^1.3.3

flutter:
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
